### ISSUE TITLE
Scrolling doesn't work in console output for test cases

### ISSUE THREAD

**Issue by briantruong777** [illinois-cs/Grade_Report#2]
Examples [here](https://subversion.ews.illinois.edu/svn/fa15-cs241/cs241svngrader/pointers_gone_wild/grade_report.html) for **Testcase: memory**.

Basically, I noticed some of it was being cut off, but actually inspecting the element shows all the text is there, but you can't scroll to view it.

@bchong95

**Comment by bchong95** [comment]
Made the log scrollable and even wrap on really long text. So that should handle vertical and horizontal overflow
