### ISSUE TITLE
Have a link to the exact revision of code that was graded.

### ISSUE THREAD

**Issue by briantruong777** [illinois-cs/Grade_Report#4]
We can have a button/link that uses the svn url parameters to show them the exact code that was graded. You can link directly to a directory in svn and any links they click on inside will also be at the same revision.

**Comment by briantruong777** [comment]
This also might require a separate revision number entry in the json file since the revision entry currently is a human readable string. We can talk details at some point.

**Comment by bchong95** [comment]
If I can get the revision number, netid, and assignment_directory then I should be able to properly link them.
